from desktop_control_center import ControlCenterApp, main
from control_center_language_runtime_v2 import install_bilingual_support
from control_center_safety_view import install_real_safety_view
from control_center_window_runtime import install_responsive_window


install_real_safety_view(ControlCenterApp)
install_bilingual_support(ControlCenterApp)
install_responsive_window(ControlCenterApp)
raise SystemExit(main())
